"""Build a 1-click Windows desktop installer for Movie Review Factory.

What it produces
----------------
A self-contained payload (embedded CPython + FFmpeg/ffprobe + yt-dlp + the app
installed into the embedded interpreter + a hidden-window VBScript launcher) and,
when Inno Setup's ``ISCC`` is available, a single ``movie-review-factory-setup-<ver>.exe``.
The end user double-clicks Setup, then a Desktop / Start-menu shortcut starts the
local server and opens ``http://localhost:8765`` — no terminal, no Python install.

Why this shape
--------------
- The heavy, moving pieces (Python runtime, FFmpeg, yt-dlp) are staged from
  pinned/official downloads into ``build/win/payload`` and cached in ``build/win/cache``.
- Everything that is pure (download plan, launcher script, ._pth patch) lives in
  small functions so it is unit-tested offline; the network / Inno steps are thin
  wrappers around those.
- Per-user install (no admin) so creators can install without IT.

Usage
-----
    py -3 scripts/package_windows.py                # stage + build the .exe (needs ISCC)
    py -3 scripts/package_windows.py --skip-iscc    # only stage the payload
    py -3 scripts/package_windows.py --extras media,semantic   # add heavy ML extras

See docs/windows-installer.md for prerequisites and code-signing guidance.
"""
from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
import urllib.request
import zipfile
from pathlib import Path

APP_NAME = "Movie Review Factory"
APP_VERSION = "0.2.0"
DEFAULT_PORT = 8765

# Pinned interpreter; override with --python-version. Embeddable amd64 build.
DEFAULT_PYTHON_VERSION = "3.12.7"
GET_PIP_URL = "https://bootstrap.pypa.io/get-pip.py"
# gyan.dev "essentials" ships ffmpeg.exe + ffprobe.exe (what the pipeline calls).
FFMPEG_ZIP_URL = "https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.zip"
YTDLP_EXE_URL = "https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp.exe"

PROJECT_ROOT = Path(__file__).resolve().parents[1]


def python_embed_url(version: str) -> str:
    return f"https://www.python.org/ftp/python/{version}/python-{version}-embed-amd64.zip"


def download_plan(cache_dir: Path, *, python_version: str = DEFAULT_PYTHON_VERSION) -> list[dict]:
    """Pure: the artifacts to fetch and where they land in the cache.

    Returned dicts have ``name``, ``url`` and ``dest`` (a path inside ``cache_dir``).
    """
    cache_dir = Path(cache_dir)
    return [
        {"name": "python-embed", "url": python_embed_url(python_version),
         "dest": cache_dir / f"python-{python_version}-embed-amd64.zip"},
        {"name": "get-pip", "url": GET_PIP_URL, "dest": cache_dir / "get-pip.py"},
        {"name": "ffmpeg", "url": FFMPEG_ZIP_URL, "dest": cache_dir / "ffmpeg-release-essentials.zip"},
        {"name": "yt-dlp", "url": YTDLP_EXE_URL, "dest": cache_dir / "yt-dlp.exe"},
    ]


def patch_embed_pth(text: str) -> str:
    """Pure: enable ``site`` + a ``Lib\\site-packages`` path in an embeddable ``._pth``.

    The embeddable distribution ships with ``import site`` commented out and no
    site-packages entry, so pip-installed packages are invisible until we turn it
    back on. Idempotent.
    """
    lines = [line.rstrip("\r\n") for line in text.splitlines()]
    out: list[str] = []
    for line in lines:
        stripped = line.strip()
        if stripped in ("#import site", "# import site"):
            out.append("import site")
        else:
            out.append(line)
    if "import site" not in out:
        out.append("import site")
    if "Lib\\site-packages" not in out and "Lib/site-packages" not in out:
        out.insert(0, "Lib\\site-packages")
    # De-dup while preserving order.
    seen: set[str] = set()
    deduped: list[str] = []
    for line in out:
        if line not in seen or line == "":
            deduped.append(line)
            seen.add(line)
    return "\n".join(deduped) + "\n"


def render_launcher_vbs(port: int = DEFAULT_PORT) -> str:
    """Pure: the hidden-window VBScript that starts the server and opens the browser."""
    return (
        "' Movie Review Factory - start the local dashboard, then open the browser.\n"
        "' Generated by scripts/package_windows.py. Runs the bundled Python with NO console window.\n"
        "Option Explicit\n"
        "Dim sh, fso, appDir, pythonExe, binDir, jobsRoot, thePort, url\n"
        "Set sh = CreateObject(\"WScript.Shell\")\n"
        "Set fso = CreateObject(\"Scripting.FileSystemObject\")\n"
        "appDir = fso.GetParentFolderName(WScript.ScriptFullName)\n"
        "pythonExe = appDir & \"\\python\\python.exe\"\n"
        "binDir = appDir & \"\\bin\"\n"
        f"thePort = {int(port)}\n"
        "url = \"http://localhost:\" & thePort & \"/\"\n"
        "jobsRoot = sh.ExpandEnvironmentStrings(\"%LOCALAPPDATA%\") & \"\\MovieReviewFactory\\jobs\"\n"
        "EnsureFolder sh.ExpandEnvironmentStrings(\"%LOCALAPPDATA%\") & \"\\MovieReviewFactory\"\n"
        "EnsureFolder jobsRoot\n"
        "' Put the bundled ffmpeg/ffprobe/yt-dlp on PATH for the spawned server.\n"
        "sh.Environment(\"PROCESS\")(\"PATH\") = binDir & \";\" & appDir & \"\\python;\" & sh.Environment(\"PROCESS\")(\"PATH\")\n"
        "' Start the server hidden (window style 0), do not wait.\n"
        "sh.Run \"\"\"\" & pythonExe & \"\"\" -m movie_review_factory serve --port \" & thePort & \" --jobs-root \"\"\" & jobsRoot & \"\"\"\", 0, False\n"
        "' Give the stdlib server a moment to bind, then open the dashboard.\n"
        "WScript.Sleep 2500\n"
        "sh.Run url, 1, False\n"
        "\n"
        "Sub EnsureFolder(p)\n"
        "  If Not fso.FolderExists(p) Then fso.CreateFolder(p)\n"
        "End Sub\n"
    )


# --------------------------------------------------------------------------- #
# Side-effecting build steps (network / filesystem / subprocess).
# --------------------------------------------------------------------------- #

def _log(message: str) -> None:
    print(f"[package-windows] {message}", flush=True)


def download(url: str, dest: Path, *, force: bool = False) -> Path:
    dest = Path(dest)
    dest.parent.mkdir(parents=True, exist_ok=True)
    if dest.is_file() and dest.stat().st_size > 0 and not force:
        _log(f"cached {dest.name}")
        return dest
    _log(f"downloading {url}")
    with urllib.request.urlopen(url) as response, open(dest, "wb") as handle:  # noqa: S310 (trusted URLs)
        shutil.copyfileobj(response, handle)
    if not dest.is_file() or dest.stat().st_size == 0:
        raise RuntimeError(f"download produced no bytes: {url}")
    return dest


def stage_python(cache: dict[str, Path], python_dir: Path, *, python_version: str) -> None:
    python_dir.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(cache["python-embed"]) as archive:
        archive.extractall(python_dir)
    pth = next(python_dir.glob("python*._pth"), None)
    if pth is None:
        raise RuntimeError("embeddable Python is missing its ._pth file")
    pth.write_text(patch_embed_pth(pth.read_text(encoding="utf-8")), encoding="utf-8")


def install_app(python_dir: Path, get_pip: Path, *, extras: list[str]) -> None:
    python_exe = python_dir / "python.exe"
    subprocess.run([str(python_exe), str(get_pip), "--no-warn-script-location"], check=True)
    target = f"{PROJECT_ROOT}[{','.join(extras)}]" if extras else str(PROJECT_ROOT)
    subprocess.run(
        [str(python_exe), "-m", "pip", "install", "--no-warn-script-location", target],
        check=True,
    )


def stage_tools(cache: dict[str, Path], bin_dir: Path) -> None:
    bin_dir.mkdir(parents=True, exist_ok=True)
    shutil.copy2(cache["yt-dlp"], bin_dir / "yt-dlp.exe")
    with zipfile.ZipFile(cache["ffmpeg"]) as archive:
        wanted = ("ffmpeg.exe", "ffprobe.exe")
        for member in archive.namelist():
            base = member.rsplit("/", 1)[-1]
            if base in wanted and not member.endswith("/"):
                with archive.open(member) as src, open(bin_dir / base, "wb") as dst:
                    shutil.copyfileobj(src, dst)
    missing = [name for name in ("ffmpeg.exe", "ffprobe.exe", "yt-dlp.exe") if not (bin_dir / name).is_file()]
    if missing:
        raise RuntimeError(f"tool staging missing: {', '.join(missing)}")


def run_iscc(iss_path: Path, payload_dir: Path, output_dir: Path, *, iscc: str, version: str) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        [iscc, f"/DMyAppVersion={version}", f"/DPayloadDir={payload_dir}",
         f"/DOutputDir={output_dir}", str(iss_path)],
        check=True,
    )


def build(args: argparse.Namespace) -> int:
    if sys.platform != "win32" and not args.skip_iscc:
        _log("WARNING: ISCC only runs on Windows; use --skip-iscc elsewhere to stage only.")
    out_root = Path(args.out)
    cache_dir = Path(args.cache)
    payload = out_root / "payload"
    if payload.exists():
        shutil.rmtree(payload)
    plan = download_plan(cache_dir, python_version=args.python_version)
    cache = {item["name"]: download(item["url"], item["dest"], force=args.force_download) for item in plan}

    stage_python(cache, payload / "python", python_version=args.python_version)
    install_app(payload / "python", cache["get-pip"], extras=[e for e in args.extras.split(",") if e.strip()])
    stage_tools(cache, payload / "bin")
    (payload / "mrf-launch.vbs").write_text(render_launcher_vbs(args.port), encoding="utf-8")
    (payload / "README.txt").write_text(
        f"{APP_NAME} {APP_VERSION}\n\nDouble-click the Desktop shortcut to start. "
        f"The dashboard opens at http://localhost:{args.port}/\n", encoding="utf-8")
    _log(f"payload staged at {payload}")

    if args.skip_iscc:
        _log("skipping ISCC (payload only)")
        return 0
    iscc = args.iscc or shutil.which("ISCC") or shutil.which("iscc")
    if not iscc:
        _log("ISCC not found on PATH; install Inno Setup 6 or pass --iscc. Payload is staged.")
        return 0
    iss_path = PROJECT_ROOT / "installer" / "movie-review-factory.iss"
    run_iscc(iss_path, payload, out_root / "dist", iscc=iscc, version=args.version)
    _log(f"installer written to {out_root / 'dist'}")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Build the Windows 1-click installer.")
    parser.add_argument("--out", default=str(PROJECT_ROOT / "build" / "win"), help="staging/output root")
    parser.add_argument("--cache", default=str(PROJECT_ROOT / "build" / "win" / "cache"), help="download cache")
    parser.add_argument("--extras", default="tts", help="comma extras to pip install (e.g. tts,media,semantic)")
    parser.add_argument("--python-version", default=DEFAULT_PYTHON_VERSION)
    parser.add_argument("--port", type=int, default=DEFAULT_PORT)
    parser.add_argument("--version", default=APP_VERSION, help="installer AppVersion")
    parser.add_argument("--iscc", default="", help="path to ISCC.exe (default: search PATH)")
    parser.add_argument("--skip-iscc", action="store_true", help="stage payload only, do not build the .exe")
    parser.add_argument("--force-download", action="store_true", help="ignore the download cache")
    return build(parser.parse_args(argv))


if __name__ == "__main__":
    raise SystemExit(main())
