"""Build a 1-click Windows desktop installer for Movie Review Factory.

What it produces
----------------
A self-contained payload (embedded CPython + FFmpeg/ffprobe + yt-dlp + the app
installed into the embedded interpreter + a hidden-window VBScript launcher) and,
when Inno Setup's ``ISCC`` is available, a single ``movie-review-factory-setup-<ver>.exe``.
The end user double-clicks Setup, then a Desktop / Start-menu shortcut starts the
local server and opens ``http://localhost:8765`` — no terminal, no Python install.

Why this shape
--------------
- The heavy, moving pieces (Python runtime, FFmpeg, yt-dlp) are staged from
  pinned/official downloads into ``build/win/payload`` and cached in ``build/win/cache``.
- Everything that is pure (download plan, launcher script, ._pth patch) lives in
  small functions so it is unit-tested offline; the network / Inno steps are thin
  wrappers around those.
- Per-user install (no admin) so creators can install without IT.

Usage
-----
    py -3 scripts/package_windows.py                # stage + build the .exe (needs ISCC)
    py -3 scripts/package_windows.py --skip-iscc    # only stage the payload
    py -3 scripts/package_windows.py --extras media,semantic   # add heavy ML extras

See docs/windows-installer.md for prerequisites and code-signing guidance.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import stat
import subprocess
import sys
import tempfile
import urllib.request
import zipfile
from pathlib import Path, PurePosixPath, PureWindowsPath

APP_NAME = "Movie Review Factory"
APP_VERSION = "0.2.0"
DEFAULT_PORT = 8765

# Pinned interpreter; override with --python-version. Embeddable amd64 build.
DEFAULT_PYTHON_VERSION = "3.12.7"
GET_PIP_URL = "https://bootstrap.pypa.io/get-pip.py"
# gyan.dev "essentials" ships ffmpeg.exe + ffprobe.exe (what the pipeline calls).
FFMPEG_ZIP_URL = "https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.zip"
YTDLP_EXE_URL = "https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp.exe"

PROJECT_ROOT = Path(__file__).resolve().parents[1]


def python_embed_url(version: str) -> str:
    return f"https://www.python.org/ftp/python/{version}/python-{version}-embed-amd64.zip"


def download_plan(
    cache_dir: Path, *, python_version: str = DEFAULT_PYTHON_VERSION,
    manifest: dict[str, dict] | None = None,
) -> list[dict]:
    """Return artifacts, optionally overlaying pinned URL and required SHA-256.

    Digests are deliberately not guessed. Release builds must supply a JSON
    manifest whose keys are artifact names and values contain ``url`` and
    ``sha256`` from the named upstream release.
    """
    cache_dir = Path(cache_dir)
    plan = [
        {"name": "python-embed", "url": python_embed_url(python_version),
         "dest": cache_dir / f"python-{python_version}-embed-amd64.zip"},
        {"name": "get-pip", "url": GET_PIP_URL, "dest": cache_dir / "get-pip.py"},
        {"name": "ffmpeg", "url": FFMPEG_ZIP_URL, "dest": cache_dir / "ffmpeg-release-essentials.zip"},
        {"name": "yt-dlp", "url": YTDLP_EXE_URL, "dest": cache_dir / "yt-dlp.exe"},
    ]
    for item in plan:
        configured = (manifest or {}).get(item["name"], {})
        item["url"] = configured.get("url", item["url"])
        item["sha256"] = configured.get("sha256", "").lower()
    return plan


def patch_embed_pth(text: str) -> str:
    """Pure: enable ``site`` + a ``Lib\\site-packages`` path in an embeddable ``._pth``.

    The embeddable distribution ships with ``import site`` commented out and no
    site-packages entry, so pip-installed packages are invisible until we turn it
    back on. Idempotent.
    """
    lines = [line.rstrip("\r\n") for line in text.splitlines()]
    out: list[str] = []
    for line in lines:
        stripped = line.strip()
        if stripped in ("#import site", "# import site"):
            out.append("import site")
        else:
            out.append(line)
    if "import site" not in out:
        out.append("import site")
    if "Lib\\site-packages" not in out and "Lib/site-packages" not in out:
        out.insert(0, "Lib\\site-packages")
    # De-dup while preserving order.
    seen: set[str] = set()
    deduped: list[str] = []
    for line in out:
        if line not in seen or line == "":
            deduped.append(line)
            seen.add(line)
    return "\n".join(deduped) + "\n"


def render_launcher_vbs(port: int = DEFAULT_PORT) -> str:
    """Pure: the hidden-window VBScript that starts the server and opens the browser."""
    return (
        "' Movie Review Factory - start the local dashboard, then open the browser.\n"
        "' Generated by scripts/package_windows.py. Runs the bundled Python with NO console window.\n"
        "Option Explicit\n"
        "Dim sh, fso, appDir, pythonExe, binDir, jobsRoot, thePort, url\n"
        "Set sh = CreateObject(\"WScript.Shell\")\n"
        "Set fso = CreateObject(\"Scripting.FileSystemObject\")\n"
        "appDir = fso.GetParentFolderName(WScript.ScriptFullName)\n"
        "pythonExe = appDir & \"\\python\\python.exe\"\n"
        "binDir = appDir & \"\\bin\"\n"
        f"thePort = {int(port)}\n"
        "url = \"http://localhost:\" & thePort & \"/\"\n"
        "jobsRoot = sh.ExpandEnvironmentStrings(\"%LOCALAPPDATA%\") & \"\\MovieReviewFactory\\jobs\"\n"
        "EnsureFolder sh.ExpandEnvironmentStrings(\"%LOCALAPPDATA%\") & \"\\MovieReviewFactory\"\n"
        "EnsureFolder jobsRoot\n"
        "' Put the bundled ffmpeg/ffprobe/yt-dlp on PATH for the spawned server.\n"
        "sh.Environment(\"PROCESS\")(\"PATH\") = binDir & \";\" & appDir & \"\\python;\" & sh.Environment(\"PROCESS\")(\"PATH\")\n"
        "' Start the server hidden (window style 0), do not wait.\n"
        "sh.Run \"\"\"\" & pythonExe & \"\"\" -m movie_review_factory serve --port \" & thePort & \" --jobs-root \"\"\" & jobsRoot & \"\"\"\", 0, False\n"
        "' Give the stdlib server a moment to bind, then open the dashboard.\n"
        "WScript.Sleep 2500\n"
        "sh.Run url, 1, False\n"
        "\n"
        "Sub EnsureFolder(p)\n"
        "  If Not fso.FolderExists(p) Then fso.CreateFolder(p)\n"
        "End Sub\n"
    )


# --------------------------------------------------------------------------- #
# Side-effecting build steps (network / filesystem / subprocess).
# --------------------------------------------------------------------------- #

def _log(message: str) -> None:
    print(f"[package-windows] {message}", flush=True)


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def download(
    url: str, dest: Path, *, sha256: str, force: bool = False,
    max_bytes: int = 1_500_000_000,
) -> Path:
    """Download transactionally and accept cache/download only after digest match."""
    if len(sha256) != 64 or any(char not in "0123456789abcdefABCDEF" for char in sha256):
        raise ValueError(f"a valid SHA-256 is required for release artifact {dest.name}")
    expected = sha256.lower()
    dest = Path(dest)
    dest.parent.mkdir(parents=True, exist_ok=True)
    if dest.is_file() and not force and sha256_file(dest) == expected:
        _log(f"cached {dest.name} (SHA-256 verified)")
        return dest
    part = dest.with_name(dest.name + ".part")
    part.unlink(missing_ok=True)
    _log(f"downloading {url}")
    try:
        request = urllib.request.Request(url, headers={"User-Agent": "movie-review-factory-packager/1"})
        with urllib.request.urlopen(request, timeout=60) as response, open(part, "xb") as handle:  # noqa: S310
            declared = response.headers.get("Content-Length")
            if declared and int(declared) > max_bytes:
                raise RuntimeError(f"download exceeds {max_bytes} byte limit: {url}")
            total = 0
            while True:
                chunk = response.read(1024 * 1024)
                if not chunk:
                    break
                total += len(chunk)
                if total > max_bytes:
                    raise RuntimeError(f"download exceeds {max_bytes} byte limit: {url}")
                handle.write(chunk)
            handle.flush()
            os.fsync(handle.fileno())
        if sha256_file(part) != expected:
            raise RuntimeError(f"SHA-256 mismatch for {url}")
        os.replace(part, dest)
    finally:
        part.unlink(missing_ok=True)
    return dest


def safe_extract_zip(archive: zipfile.ZipFile, destination: Path) -> None:
    """Extract regular files only; reject traversal, Windows roots and links."""
    destination.mkdir(parents=True, exist_ok=True)
    root = destination.resolve()
    for info in archive.infolist():
        posix = PurePosixPath(info.filename)
        windows = PureWindowsPath(info.filename)
        mode = info.external_attr >> 16
        if (not info.filename or posix.is_absolute() or windows.is_absolute()
                or windows.drive or ".." in posix.parts or ".." in windows.parts
                or stat.S_ISLNK(mode) or (info.external_attr & 0x400)):
            raise RuntimeError(f"unsafe ZIP member: {info.filename!r}")
        target = destination.joinpath(*posix.parts)
        if os.path.commonpath((str(root), str(target.resolve()))) != str(root):
            raise RuntimeError(f"unsafe ZIP member: {info.filename!r}")
        if info.is_dir():
            target.mkdir(parents=True, exist_ok=True)
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            with archive.open(info) as src, open(target, "xb") as dst:
                shutil.copyfileobj(src, dst)


def stage_python(cache: dict[str, Path], python_dir: Path, *, python_version: str) -> None:
    python_dir.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(cache["python-embed"]) as archive:
        safe_extract_zip(archive, python_dir)
    pth = next(python_dir.glob("python*._pth"), None)
    if pth is None:
        raise RuntimeError("embeddable Python is missing its ._pth file")
    pth.write_text(patch_embed_pth(pth.read_text(encoding="utf-8")), encoding="utf-8")


def install_app(python_dir: Path, get_pip: Path, *, extras: list[str]) -> None:
    python_exe = python_dir / "python.exe"
    subprocess.run([str(python_exe), str(get_pip), "--no-warn-script-location"], check=True)
    target = f"{PROJECT_ROOT}[{','.join(extras)}]" if extras else str(PROJECT_ROOT)
    subprocess.run(
        [str(python_exe), "-m", "pip", "install", "--no-warn-script-location", target],
        check=True,
    )


def stage_tools(cache: dict[str, Path], bin_dir: Path) -> None:
    bin_dir.mkdir(parents=True, exist_ok=True)
    shutil.copy2(cache["yt-dlp"], bin_dir / "yt-dlp.exe")
    with zipfile.ZipFile(cache["ffmpeg"]) as archive:
        wanted = ("ffmpeg.exe", "ffprobe.exe")
        for info in archive.infolist():
            posix = PurePosixPath(info.filename)
            windows = PureWindowsPath(info.filename)
            mode = info.external_attr >> 16
            if (posix.is_absolute() or windows.is_absolute() or windows.drive
                    or ".." in posix.parts or stat.S_ISLNK(mode)):
                raise RuntimeError(f"unsafe ZIP member: {info.filename!r}")
            base = posix.name
            if base in wanted and not info.is_dir():
                with archive.open(info) as src, open(bin_dir / base, "xb") as dst:
                    shutil.copyfileobj(src, dst)
    missing = [name for name in ("ffmpeg.exe", "ffprobe.exe", "yt-dlp.exe") if not (bin_dir / name).is_file()]
    if missing:
        raise RuntimeError(f"tool staging missing: {', '.join(missing)}")


def run_iscc(iss_path: Path, payload_dir: Path, output_dir: Path, *, iscc: str, version: str) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        [iscc, f"/DMyAppVersion={version}", f"/DPayloadDir={payload_dir}",
         f"/DOutputDir={output_dir}", str(iss_path)],
        check=True,
    )


def build(args: argparse.Namespace) -> int:
    if sys.platform != "win32" and not args.skip_iscc:
        _log("WARNING: ISCC only runs on Windows; use --skip-iscc elsewhere to stage only.")
    out_root = Path(args.out)
    cache_dir = Path(args.cache)
    payload = out_root / "payload"
    manifest = json.loads(Path(args.download_manifest).read_text(encoding="utf-8"))
    plan = download_plan(cache_dir, python_version=args.python_version, manifest=manifest)
    cache = {
        item["name"]: download(
            item["url"], item["dest"], sha256=item["sha256"], force=args.force_download,
        ) for item in plan
    }

    out_root.mkdir(parents=True, exist_ok=True)
    staging = Path(tempfile.mkdtemp(prefix="payload-", dir=out_root))
    backup = out_root / "payload.last-known-good"
    try:
        stage_python(cache, staging / "python", python_version=args.python_version)
        install_app(staging / "python", cache["get-pip"], extras=[e for e in args.extras.split(",") if e.strip()])
        stage_tools(cache, staging / "bin")
        (staging / "mrf-launch.vbs").write_text(render_launcher_vbs(args.port), encoding="utf-8")
        (staging / "README.txt").write_text(
            f"{APP_NAME} {APP_VERSION}\n\nDouble-click the Desktop shortcut to start. "
            f"The dashboard opens at http://localhost:{args.port}/\n", encoding="utf-8")
        required = (staging / "python" / "python.exe", staging / "bin" / "ffmpeg.exe",
                    staging / "bin" / "ffprobe.exe", staging / "bin" / "yt-dlp.exe",
                    staging / "mrf-launch.vbs")
        if not all(path.is_file() and path.stat().st_size > 0 for path in required):
            raise RuntimeError("staged payload failed validation")
        if backup.exists():
            shutil.rmtree(backup)
        if payload.exists():
            os.replace(payload, backup)
        try:
            os.replace(staging, payload)
        except Exception:
            if backup.exists() and not payload.exists():
                os.replace(backup, payload)
            raise
    finally:
        if staging.exists():
            shutil.rmtree(staging)
    _log(f"payload staged at {payload}")

    if args.skip_iscc:
        _log("skipping ISCC (payload only)")
        return 0
    iscc = args.iscc or shutil.which("ISCC") or shutil.which("iscc")
    if not iscc:
        _log("ISCC not found on PATH; install Inno Setup 6 or pass --iscc. Payload is staged.")
        return 0
    iss_path = PROJECT_ROOT / "installer" / "movie-review-factory.iss"
    run_iscc(iss_path, payload, out_root / "dist", iscc=iscc, version=args.version)
    _log(f"installer written to {out_root / 'dist'}")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Build the Windows 1-click installer.")
    parser.add_argument("--out", default=str(PROJECT_ROOT / "build" / "win"), help="staging/output root")
    parser.add_argument("--cache", default=str(PROJECT_ROOT / "build" / "win" / "cache"), help="download cache")
    parser.add_argument("--extras", default="tts", help="comma extras to pip install (e.g. tts,media,semantic)")
    parser.add_argument("--python-version", default=DEFAULT_PYTHON_VERSION)
    parser.add_argument("--download-manifest", required=True,
                        help="JSON mapping artifact names to pinned url + sha256")
    parser.add_argument("--port", type=int, default=DEFAULT_PORT)
    parser.add_argument("--version", default=APP_VERSION, help="installer AppVersion")
    parser.add_argument("--iscc", default="", help="path to ISCC.exe (default: search PATH)")
    parser.add_argument("--skip-iscc", action="store_true", help="stage payload only, do not build the .exe")
    parser.add_argument("--force-download", action="store_true", help="ignore the download cache")
    return build(parser.parse_args(argv))


if __name__ == "__main__":
    raise SystemExit(main())
